version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
  post_build:
    commands:
    

artifacts:
  files:
    - '**/*'
  